// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package DomainResponse

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson544ac6d1DecodeUsersDorontabakmanGoSrc(in *jlexer.Lexer, out *DomainResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "location":
			out.Location = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson544ac6d1EncodeUsersDorontabakmanGoSrc(out *jwriter.Writer, in DomainResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"location\":"
		out.RawString(prefix[1:])
		out.String(string(in.Location))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DomainResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson544ac6d1EncodeUsersDorontabakmanGoSrc(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DomainResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson544ac6d1EncodeUsersDorontabakmanGoSrc(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DomainResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson544ac6d1DecodeUsersDorontabakmanGoSrc(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DomainResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson544ac6d1DecodeUsersDorontabakmanGoSrc(l, v)
}
