// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package DomainRequest

import (
	"encoding/json"
	"github.com/mailru/easyjson"
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC889dccdDecodeUsersDorontabakmanGoSrc(in *jlexer.Lexer, out *DomainRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "domain":
			out.Domain = string(in.String())
		case "path":
			out.Path = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC889dccdEncodeUsersDorontabakmanGoSrc(out *jwriter.Writer, in DomainRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"path\":"
		out.RawString(prefix)
		out.String(string(in.Path))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DomainRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC889dccdEncodeUsersDorontabakmanGoSrc(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DomainRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC889dccdEncodeUsersDorontabakmanGoSrc(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DomainRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC889dccdDecodeUsersDorontabakmanGoSrc(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DomainRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC889dccdDecodeUsersDorontabakmanGoSrc(l, v)
}
